### ISSUE TITLE
App does not load in Firefox

### ISSUE THREAD

**Issue by returnx** [returnx/swifteamqa#1]
Launch the App
https://app.dev.swifteam.com/org/team/employees

Login and wait for load
The app will be stuck in a loop

This issue now happens in Chrome as well, try with these login details. Try in an InCognito Tab.
https://app.dev.swifteam.com/
contact@akshayy.com
Swift0101

![1](https://user-images.githubusercontent.com/9914270/223720507-b52cb446-7e93-4710-8f83-e49ade23fa44.png)

**Comment by angelorobo** [comment]
I'm not able to duplicate the issue.
![image](https://user-images.githubusercontent.com/51975997/224142214-e1384d31-95d7-4892-9ca0-e7317f857f49.png)
