### ISSUE TITLE
Adding an employee without Region, does not throw the correct error notification

### ISSUE THREAD

**Issue by returnx** [returnx/swifteamqa#11]
Login and go to All Employees page

https://app.dev.swifteam.com/org/team/employees

Now try to add an employee, don't input the Region/Country

An error notification is thrown, but  this message does not provide the reason. The notification should say region/country is required.

![image](https://user-images.githubusercontent.com/9914270/223739318-49bb140f-7eef-4d90-b123-12f57929cb59.png)

**Comment by angelorobo** [comment]
I can not replicate this issue
