### ISSUE TITLE
Quickstart dialog will overlay on top of "Add Unlimited Employess now" dialog

### ISSUE THREAD

**Issue by returnx** [returnx/swifteamqa#2]
Now this happens when Quick Start is enabled and not turn off by the user and the user is a trial user.

What actually happens is the upsell dialog first loads and then Quick start dialog loads and covers the Upgrade dialog.

I am attaching a screenshot, however in this screenshot its the opposite. 
This however is an issue and needs to be handled better in the future

![2](https://user-images.githubusercontent.com/9914270/223721144-dd1aa060-bdb8-4420-841c-8d48b370a8ba.png)

**Comment by angelorobo** [comment]
Jira ticket created
