### ISSUE TITLE
UX issue, selected employee in the list should have a checkmark

### ISSUE THREAD

**Issue by returnx** [returnx/swifteamqa#4]
If you compare the On boarding employee drop-down with the UX, the check mark for selected employee is missing.

Actual - 
![3](https://user-images.githubusercontent.com/9914270/223723643-14acbdd9-7475-4d4f-b4b4-c3ed725b6eaf.png)

As in the UIX
https://cdn.zeplin.io/63ffa4f5e1b6865319ea6517/screens/54E2A1B1-7554-4972-86F7-DC90EC0F417E.png

**Comment by angelorobo** [comment]
Jira ticket is created
