### ISSUE TITLE
Learn More URLs don't do anything in the Account activation page

### ISSUE THREAD

**Issue by returnx** [returnx/swifteamqa#6]
In the On-boarding workflow, Learn More URLs don't work.

If you click them, nothing happens. Normally they should navigate the user to a help page in a new tab.

![6](https://user-images.githubusercontent.com/9914270/223724855-5c4b151a-500a-4826-b7d7-f8f0818e036b.png)

**Comment by angelorobo** [comment]
I created a jira to follow up
