### ISSUE TITLE
Success dialog does not close in the Equipment User Agreement Page

### ISSUE THREAD

**Issue by returnx** [returnx/swifteamqa#7]
Onboard an employee and assign a device to the employee
The user goes to the agreement page, signs the agreement

The success dialog shows up.
Now the user can can't close the dialog by clicking OK
Clicking OK does nothing.

![9](https://user-images.githubusercontent.com/9914270/223725960-5038ac55-68ff-45e3-891c-02f515e77e5b.png)

**Comment by angelorobo** [comment]
This is fixed
